Frame App v7 support
mainframe2/FrameApp-IGEL-Custom-Partitions pull request #1
Opened 2024-08-23 09:26 UTC by alexandarZ

Updated IGEL Custom partition with the following items:

* Updated README.md with new latest app releases
* Updated bash scripts for SAT and SAML2 kiosk launchers to support app v6 and v7
* Updated SAT kiosk launcher with fix for Aurora University customer
*  Added IGEL UMS12 profiles:
   - Basic Frame App profile
   - SAT kiosk launcher profile
   - SAML2 kiosk launcher profile

2024-09-02 08:51 UTC, filipLazic41 approved these changes

2024-09-02 09:07 UTC, marko-sosic approved these changes

2024-09-03 18:29 UTC, ALR1990 requested changes
Just need to adjust the URL for the command line arguments. Looks good!

2024-09-03 18:29 UTC, ALR1990 commented on CP_Source/Apps/Frame/README.md
> +Command line arguments for Frame app are defined here: [Linux command-line arguments](https://docs.fra.me/platform/session/frame-app/config/?operating-systems=linux#frapp-args).
Should be:
https://docs.dizzion.com/platform/session/frame-app/config#command-line-arguments

2024-09-03 18:29 UTC, ALR1990 commented on CP_Source/Apps/Frame/README.md
> +Command line arguments for Frame app are defined here: [Linux command-line arguments](https://docs.fra.me/platform/session/frame-app/config/?operating-systems=linux#frapp-args).
Linux is under its own tab

2024-09-26 11:55 UTC, merged